#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(KC_Q, KC_W, KC_F, KC_P, KC_G, KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_A, KC_R, KC_S, KC_T, KC_D, KC_H, KC_N, KC_E, KC_I, KC_O, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_K, KC_M, KC_COMM, KC_DOT, KC_SLSH, LT(3,KC_ESC), LT(2,KC_TAB), KC_LALT, KC_LSFT, KC_BSPC, MO(1), KC_LGUI, KC_SPC, KC_LCTL, KC_MINS, KC_QUOT, KC_ENT),
	[1] = LAYOUT(KC_EXLM, KC_7, KC_8, KC_9, KC_PGUP, KC_LCBR, KC_RCBR, KC_UP, KC_AT, KC_ASTR, KC_HASH, KC_4, KC_5, KC_6, KC_PGDN, KC_DLR, KC_LEFT, KC_DOWN, KC_RGHT, KC_PLUS, KC_BSLS, KC_1, KC_2, KC_3, KC_0, KC_GRV, KC_LPRN, KC_RPRN, KC_LBRC, KC_RBRC, KC_NO, KC_INS, KC_DOT, KC_LSFT, KC_BSPC, KC_LCTL, KC_LALT, KC_ENT, KC_TRNS, KC_LGUI, KC_AMPR, KC_EQL),
	[2] = LAYOUT(KC_NO, KC_7, KC_8, KC_9, KC_NO, KC_UP, KC_F7, KC_F8, KC_F9, KC_F10, KC_NO, KC_4, KC_5, KC_6, KC_NO, KC_DOWN, KC_F4, KC_F5, KC_F6, KC_F11, KC_NO, KC_1, KC_2, KC_3, KC_NO, TG(0), KC_F1, KC_F2, KC_F3, KC_F12, KC_NO, KC_P0, KC_PDOT, KC_LSFT, KC_BSPC, KC_LCTL, KC_LALT, KC_SPC, RESET, KC_TRNS, KC_SLCK, KC_PAUS),
	[3] = LAYOUT(KC_ESC, KC_WH_U, KC_WBAK, KC_WFWD, KC_NO, KC_PGUP, KC_HOME, KC_UP, KC_END, KC_DEL, KC_LALT, KC_WH_D, KC_LSFT, KC_LCTL, KC_NO, KC_PGDN, KC_LEFT, KC_DOWN, KC_RGHT, KC_BSPC, RCTL(KC_Z), RCTL(KC_X), RCTL(KC_C), RCTL(KC_V), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_ENT, KC_NO, TG(2), KC_NO, KC_NO)
};
