#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(KC_Q, KC_W, KC_F, KC_P, KC_G, KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_A, KC_R, KC_S, KC_T, KC_D, KC_H, KC_N, KC_E, KC_I, KC_O, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_K, KC_M, KC_COMM, KC_DOT, KC_SLSH, LT(2,KC_ESC), LT(3,KC_TAB), KC_LSFT, KC_LCTL, KC_BSPC, KC_LGUI, MO(1), KC_SPC, KC_LALT, KC_MINS, KC_QUOT, KC_ENT),
	[1] = LAYOUT(KC_EXLM, KC_9, KC_8, KC_7, KC_PGUP, KC_RCBR, KC_LCBR, KC_UP, KC_AT, KC_ASTR, KC_HASH, KC_6, KC_5, KC_4, KC_PGDN, KC_DLR, KC_RGHT, KC_DOWN, KC_LEFT, KC_PLUS, KC_BSLS, KC_3, KC_2, KC_1, KC_AMPR, KC_GRV, KC_RPRN, KC_LPRN, KC_RBRC, KC_LBRC, KC_NO, KC_INS, KC_DOT, KC_LSFT, KC_BSPC, KC_LCTL, KC_LALT, KC_ENT, KC_TRNS, KC_LGUI, KC_0, KC_EQL),
	[2] = LAYOUT(KC_INS, KC_HOME, KC_UP, KC_END, KC_PGUP, KC_UP, KC_F7, KC_F8, KC_F9, KC_F10, KC_DEL, KC_LEFT, KC_DOWN, KC_RGHT, KC_PGDN, KC_DOWN, KC_F4, KC_F5, KC_F6, KC_F11, KC_NO, KC_VOLU, KC_NO, KC_NO, RESET, KC_NO, KC_F1, KC_F2, KC_F3, KC_F12, KC_NO, KC_VOLD, KC_LGUI, KC_LSFT, KC_BSPC, KC_LCTL, KC_LALT, KC_SPC, KC_NO, KC_PSCR, KC_SLCK, KC_PAUS),
	[3] = LAYOUT(KC_NO, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_DLR, KC_PERC, KC_CIRC, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_EXLM, KC_AT, KC_HASH, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};
